services:
  backend:
    build: ./backend

    ports:
      - 3000:3000

  frontend:
    build: ./Frontend
    ports:
      - 5173:5173
    depends_on:
      - backend

  server:
    build: ./Frontend/server
    ports:
      - 5001:5001
    depends_on:
      - backend
